---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservicedemo-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: microservicedemo
    spec:
      containers:
      - name: microservicedemo
        image: jthompson109/microservicedemo:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
  selector:
    matchLabels:
      app: microservicedemo
---
apiVersion: v1
kind: Service
metadata:
  name: microservicedemo-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: microservicedemo
