//initial code was generated by "tsrpfc" commend from the "Typescript React Code Snippets Extension"
import React, {FC, useState} from 'react';
import { HairColor } from './Enums';



interface IAppProps {
    name?: string; //Question mark makes property optional
    age: number;
    email: string;
    hairColor: HairColor;
   // getName: (name: string) => string; //defining a function in interface
}

export const Person = (props: IAppProps) => {
    const [country, setCountry] = useState<string | null>("")

    //Type example
    type NameType = "Joe" | "Jossy";
    const nameForType: NameType ="Joe";
//End type example

    const handleChange = (event: React.ChangeEvent<HTMLInputElement>) => {
        setCountry(event.target.value)
    }

  return (
    <div>
      <h1>{props.name}</h1>
      <h1>{props.email}</h1>
      <h1>{props.age}</h1>
      <h1>{props.hairColor}</h1>
      <input placeholder='Enter your country...' 
      onChange={handleChange} />

      {country}
    </div>
  );
}

/*Functional Component Version of this:
at the top: 
import {FC} from 'react';

THEN:
export const Person: FC<Props> = (name, age, email) => {
  return (
    <div>
      <h1>{name}</h1>
      <h1>{email}</h1>
      <h1>{age}</h1>
    </div>
  );
}

*/
